In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [57]:
df = pd.read_csv('Warehouses_v2.csv')
df.head()

,warehouse_id,warehouse_name,city,state,warehouse_type,capacity,internal_note
0,1,WH-00001,Seattle,Washington,Fulfillment Center,73160,INT-T5GIBEA
1,2,WH-00002,Chicago,Illinois,Distribution Center,72333,INT-YKWV1YM
2,3,WH-00003,Dallas,Texas,Fulfillment Center,42057,INT-WECD8DW
3,4,WH-00004,Phoenix,Arizona,Fulfillment Center,9587,INT-MDRGE01
4,5,WH-00005,New York,New York,Cross Dock,93305,INT-8YZ0Z43

In [58]:
df.shape

(10126, 7)

In [59]:
df.dtypes

warehouse_id       int64
warehouse_name    object
city              object
state             object
warehouse_type    object
capacity           int64
internal_note     object
dtype: object

In [60]:
df.isnull().sum()   #2% Null values

warehouse_id        0
warehouse_name      0
city              202
state               0
warehouse_type      0
capacity            0
internal_note       0
dtype: int64

In [61]:
df['warehouse_id'].nunique()

10025

In [62]:
df['city'].value_counts()

city
Phoenix         728
Portland        694
Detroit         683
Austin          681
Denver          663
Atlanta         662
Charlotte       661
New York        657
Seattle         656
Dallas          655
Houston         647
Boston          645
Miami           620
Chicago         609
Los Angeles     586
HOUSTON          13
New york         11
Los angeles      11
Chicago           9
CHICAGO           6
LOS ANGELES       6
 Houston          5
 Los Angeles      5
chicago           5
 New York         4
NEW YORK          2
Name: count, dtype: int64

In [63]:
df['city']=df['city'].str.title().str.strip()

In [64]:
df['state'].nunique()

14

In [65]:
df['city'] = df['city'].fillna(df.groupby('state')['city'].transform(lambda x:x.mode()[0]))

In [66]:
df.isnull().sum()

warehouse_id      0
warehouse_name    0
city              0
state             0
warehouse_type    0
capacity          0
internal_note     0
dtype: int64

In [67]:
df['city'].value_counts()

city
Los Angeles    810
Phoenix        728
Portland       694
Detroit        683
Austin         681
New York       674
Houston        665
Denver         663
Atlanta        662
Charlotte      661
Seattle        656
Dallas         655
Boston         645
Chicago        629
Miami          620
Name: count, dtype: int64

In [68]:
df.duplicated().sum()

np.int64(28)

In [69]:
df.drop_duplicates(inplace=True)

In [70]:
df.drop(columns=['internal_note'],inplace=True)
df.head()

,warehouse_id,warehouse_name,city,state,warehouse_type,capacity
0,1,WH-00001,Seattle,Washington,Fulfillment Center,73160
1,2,WH-00002,Chicago,Illinois,Distribution Center,72333
2,3,WH-00003,Dallas,Texas,Fulfillment Center,42057
3,4,WH-00004,Phoenix,Arizona,Fulfillment Center,9587
4,5,WH-00005,New York,New York,Cross Dock,93305

In [71]:
df.to_csv('warehouse.csv',index=False)